app/controllers/bookings_controller.rb, app/controllers/gardens_controller.rb, app/views/bookings/index.html.erb, app/views/bookings/show.html.erb, app/views/gardens/show.html.erb, config/routes.rb, test/controllers/bookings_controller_test.rb
I have coded the views very basically just so we know that it works on the backend
=> Created a bookings controller with show, index, new and create

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
a basic homepage with link to gardens index
=> homepage skeleton set up

app/controllers/bookings_controller.rb, app/views/bookings/edit.html.erb, app/views/bookings/index.html.erb, app/views/bookings/show.html.erb
Added edit and update into bookings controller and edit view. 
Also updated bookings index to link_to bookings show.
Refactored bookings controller with before_action.
=> adding edit and update for bookings

app/views/bookings/show.html.erb, db/migrate/20210513191436_add_features_to_gardens.rb, db/schema.rb
Added the 5 features to the Garden model.
Migration created. Set default values to false.
Booking Show page updated to show is BBQ (only BBQ at this stage in the show) is true.
NB: After git pull master origin run rails db:migrate
=> added 5 boolean garden features

app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
=> updated the home-page style

app/controllers/bookings_controller.rb, app/controllers/gardens_controller.rb, app/controllers/reviews_controller.rb, app/models/booking.rb, app/views/bookings/show.html.erb, app/views/gardens/show.html.erb, app/views/reviews/new.html.erb, config/routes.rb, test/controllers/reviews_controller_test.rb
Created the reviews controller and rendered a review form on the bookings show page
Also rendered reviews on the gardens show page
=> Create review controller

app/controllers/gardens_controller.rb, app/views/bookings/show.html.erb, app/views/gardens/edit.html.erb, app/views/gardens/show.html.erb
Added 5 features to 
- Garden Show
- Booking Show
- Garden Edit
- Updated Permitted Params
**Garden Show**
**Booking Show**
**Garden Edit**
=> 5 Features Added

Gemfile, Gemfile.lock, app/controllers/gardens_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/models/garden.rb, app/views/gardens/index.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, config/initializers/geocoder.rb, db/migrate/20210515093709_remove_postcode_from_gardens.rb, db/migrate/20210515095957_add_coordinates_to_gardens.rb, db/schema.rb, db/seeds.rb, package.json, yarn.lock
Added map with markers to index page, this also involved adding latitude and longitude to the garden models.
=> Added map to index page

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/views/gardens/index.html.erb
=> All my booking frontend

app/views/gardens/show.html.erb
Just removed the postcode from the show page to stop it breaking
=> removed postcode from show page

app/views/bookings/index.html.erb, app/views/gardens/index.html.erb, db/seeds.rb
add card and nav bar in this page. 
nav bar is not link yet
=> All my bookings page view

app/views/shared/_navbar.html.erb
Added see all my bookings to drop down list.
=> added see my bookings to drop down list

.gitignore, app/assets/stylesheets/pages/_booking.scss, app/assets/stylesheets/pages/_index.scss, app/views/bookings/index.html.erb
- change to row instead of flex
- rounded cards
- add -booking.scss file
=> All my bookings page changes

app/views/bookings/index.html.erb
=> Polish my bookings page merge

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_quotecard.scss, app/assets/stylesheets/components/_scrollcard.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Including scrolling garden cards and green quotes section
=> Updates to homepage css below hero image 

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/controllers/gardens_controller.rb, app/javascript/plugins/init_mapbox.js, app/views/gardens/_info_window.html.erb, app/views/gardens/index.html.erb
Added the info windows to the map with title, price and link to show page, also fixed the spacing issues on the index page.
=> Map info windows added

app/assets/stylesheets/pages/_show.scss, app/views/gardens/show.html.erb
=> made the feature greyed out if not applicable

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/views/gardens/new.html.erb
=> Form frontend

app/assets/stylesheets/components/_navbar.scss
Nav bar now sits above all other elements including images.
=> updated z index of nav bar

app/assets/stylesheets/components/_map.scss, app/javascript/plugins/init_mapbox.js, app/javascript/plugins/init_mapbox_garden_show.js
=> added styling to the maps = favicon

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/views/bookings/index.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/gardens/new.html.erb
=> style simply_form_for : Login form/ create garden form

app/views/pages/home.html.erb
I didn't have time to sample them uniquely so for now the reviews on the homepage will always be the same ones but demo wise no one has to know...
=> made reviews unique
